### ISSUE TITLE
URL problem when it has arguments

### ISSUE THREAD

**Issue by kanodoe** [kriskbx/whatsapp-sharing#20]
Hi,

I try to use an url with arguments (Google Analytics Campaign)  in the **data-href** and it opens Whatsapp but after chose the receiver the message is empty (not even the title).

There is the example that fails:
``` <a href="whatsapp://send" data-text="Ay&uacute;danos a conseguir donaciones:" data-href="http://www.ayudemosajulio.cl/?utm_source=social_share&utm_medium=whatsapp&utm_campaign=ayudemosajulio" class="wa_btn wa_btn_s" style="display:none">Compartir</a>```

And this one works fine:
```<a href="whatsapp://send" data-text="Ay&uacute;danos a conseguir donaciones:" data-href="http://www.ayudemosajulio.cl" class="wa_btn wa_btn_s" style="display:none">Compartir</a>```

**Comment by nikhilprasad11** [comment]
use %26 instead on & in case of arguments :-)

**Comment by kriskbx** [comment]
Sorry for the late answer. Have you tried the newest version yet?

**Comment by kanodoe** [comment]
Actually no, when I back from my vacations I will test if it works.


Thanks!

Alejandro Cornejo Sepúlveda
Diseñador Gráfico Multimedia

Tel: +562 2 897 7015
Cel: +569 9 7333253
Email: acornejo@mousecatcher.cl

www.mousecatcher.cl

En 15 de abril de 2015 en 16:46:30, kris dot cool (notifications@github.com) escrito:

Sorry for the late answer. Have you tried the newest version yet?
