### ISSUE TITLE
WhatApp Sharing Button does not sharing...

### ISSUE THREAD

**Issue by Ankamz** [kriskbx/whatsapp-sharing#23]
Dear team,
i've a issue with a WhatsApp Sharing Button. I followed all the instructions given to you but when I click on share , not shown any link , which could be the problem ? The website in question is www.finanziamentipergiovani.it

while I wait for your help I wish you a good job!

And

**Comment by Ipno84** [comment]
The website you're talking about is not developed for smartphone. So I think it couldn't be necessary to insert whatsapp button. I think you need to take care about tablet and smartphone versions if you need to use whatsapp sharing button. However, the WhatsApp Sharing Button code look for navigator object. If you take a look at your website with a smartphone the whatsapp sharing button is rendered (tested with oneplus one, Android 4.4.4, chrome mobile)
