### ISSUE TITLE
Whatsapp Sharing button does not work

### ISSUE THREAD

**Issue by leongg** [kriskbx/whatsapp-sharing#24]
Hi, i have this code:

<a href="whatsapp://send" data-text="Ayudanos a resolver el desafío:" data-href="http://<%= @current_account.domain %>/desafios/<%= @challenge.id %>" class="wa_btn wa_btn_l visible-xs" style="display:none">Compartir en Whatsapp</a> 

and is not working, when I check on my phone http://a.kiknow.com:3001/desafios/53 does not work and even in my website http://eltaller.tedesafia.com/desafios/341 

please can you help me? Thanks for you help!

**Comment by Ipno84** [comment]
Both the link you wrote return and error on mobile browser. I don't know how to help you but the problem is not about the whatsapp sharing button

**Comment by leongg** [comment]
Thanks for you help!

This is the code <a href="whatsapp://send" data-text="Ayudanos a resolver el desafío:" data-href="http://<%= @current_account.domain %>/desafios/<%= @challenge.id %>" class="wa_btn wa_btn_l visible-xs" style="display:none">Compartir en Whatsapp</a>  

I guess I followed everything

**Comment by Ipno84** [comment]
Sorry @leongg but I can't see the code. Maybe you can use http://plnkr.co/ to show us your code

**Comment by leongg** [comment]
http://plnkr.co/edit/eiGmFw?p=info can you see it?

**Comment by leongg** [comment]
http://plnkr.co/eiGmFw or that should work

**Comment by Ipno84** [comment]
Ok, i think I've found the solution. I took a look at chrome console and I found this:
http://tedesafia.tld/path/whatsapp-button.js Failed to load resource: net::ERR_NAME_NOT_RESOLVED
I think that the path of your whatsapp-button.js is not correct. You have to change that with the correct one, In fact the button is not rendered in an iframe as it should be. Let me know if it's the right solution

**Comment by leongg** [comment]
Thanks !!!!!!!! it is working perfect!
