### ISSUE TITLE
Cannot Open Page error

### ISSUE THREAD

**Issue by yetkinyuce** [kriskbx/whatsapp-sharing#25]
Hi, 

If a user doesn't have the what's app installed, and clicked on the button they see the "Cannot Open Page" pop-up on iOS, and on Android the link is broken. 

Would there be a way to let users know that they have to install What's App for sharing instead of these pop-ups or broken links?

Please refer to the attached image:
![ios-android](https://cloud.githubusercontent.com/assets/7622212/6025696/a0670d0c-aba2-11e4-81ce-c1db6e69746e.jpg)

**Comment by kriskbx** [comment]
This isn't possible at all.
