### ISSUE TITLE
Button did not work on Nokia Lumia and Blackberry - FIXED

### ISSUE THREAD

**Issue by konstantinlangjahr** [kriskbx/whatsapp-sharing#27]
Hi, 
I had the issue, that the buttons did not work on mentioned devices. I figured what, what caused the Problem:

I changed the following lines of Code:
button.js:
FROM:
waShBtn.prototype.isIos = ((navigator.userAgent.match(/Android|iPhone/i) && !navigator.userAgent.match(/iPod|iPad/i)) ? true : false);

TO:
waShBtn.prototype.isIos = ((navigator.userAgent.match(/Windows Phone/i|/BlackBerry/i|/Android|iPhone/i) && !navigator.userAgent.match(/iPod|iPad/i)) ? true : false);

whatsapp-button.js:
FROM:
this.isIos === !0 && this.cntLdd(window, this.crBtn)
}, waShBtn.prototype.isIos = navigator.userAgent.match(/Android|iPhone/i) && !navigator.userAgent.match(/iPod|iPad/i) ? !0 : !1, waShBtn.prototype.cntLdd

TO:
this.isIos === !0 && this.cntLdd(window, this.crBtn)
}, waShBtn.prototype.isIos = navigator.userAgent.match(/Windows Phone/i|/BlackBerry/i|/Android|iPhone/i) && !navigator.userAgent.match(/iPod|iPad/i) ? !0 : !1, waShBtn.prototype.cntLdd

Best regards

**Comment by kriskbx** [comment]
I can't test on this devices. If you want to contribute, make a pull request.
