### ISSUE TITLE
CSS not loaded

### ISSUE THREAD

**Issue by domfitty** [kriskbx/whatsapp-sharing#33]
http://www.corodiocesidiroma.com/concerto-aula-paolo-vi.html
I embeded whatsapp button here but It seems not work.

If I remove display:none code, I see the link (only text) and it opens whatsapp app.

It seems not load the css.

**Comment by janniconl** [comment]
Try including the minified version: https://github.com/kriskbx/whatsapp-sharing/blob/master/dist/whatsapp-button.js

**Comment by domfitty** [comment]
http://www.corodiocesidiroma.com/magistero.html

It doesn't work :-( Still the same

**Comment by janniconl** [comment]
You're not including the JS file as far as I can see: http://www.corodiocesidiroma.com/2014/jsb/whatsapp-button.js
