### ISSUE TITLE
CommonJS/AMD build & push to npm?

### ISSUE THREAD

**Issue by Bartvds** [kriskbx/whatsapp-sharing#35]
We'd like to use this in our webpack based build, so we'd like this as a CommonJS (or UMD) module.

I also see a package.json so maybe it is cool to push to npm as well.

**Comment by kriskbx** [comment]
I will publish it to NPM very soon and update the readme then as well.
CommonJS is obsoleted by Node.js - maybe it's time to move on. ;)

**Comment by kriskbx** [comment]
The library is now available via Npm: `npm install --save whatsapp-sharing`
