### ISSUE TITLE
Button Design

### ISSUE THREAD

**Issue by EhliTevhid** [kriskbx/whatsapp-sharing#36]
How to design button ? 
Example: http://ehlitevhid.com/forums/index.php?showtopic=78
![2015-03-15_2224](https://cloud.githubusercontent.com/assets/6430175/6657314/24d4999a-cb62-11e4-91bb-60fa970a920f.png)
How to do that buttons to have the same design? Rather, facebook and twitter freak to be in the same way as it is. Currently, different buttons

**Comment by kriskbx** [comment]
The library was not made to be heavily modified. If you like to use your own design, feel free to fork the repository and build your own button upon it - after all it's just a browsercheck and an url-scheme.
