### ISSUE TITLE
iOS not work

### ISSUE THREAD

**Issue by nkuldip** [kriskbx/whatsapp-sharing#43]
When I try this on Iphone, it gives you the possible to select a contact, but there is nothing to share. It remains empty.

**Comment by kriskbx** [comment]
Noone can help you without code to look at.
Read this first: https://github.com/kriskbx/whatsapp-sharing/blob/master/ISSUES.md

**Comment by nkuldip** [comment]
Hello @kriskbx 

Here is code
<?php
$title="Test Title";
$url="http://www.whatsapp.com";


$btn = '<a href="whatsapp://send?text='.$title.' - '.$url.'">Share this on WhatsApp</a>';

echo $btn;	
?>

**Comment by kriskbx** [comment]
This code doesn't help: this is regular PHP and it simply echos out a string somewhere, it's not related to the library in any way.
Have you integrated the library into your website? Then provide us with a link to your site or paste the **resulting** code into a jsfiddle or something. I'm interested in the actual button html element as well as the inclusion of the js-library.

**Comment by nkuldip** [comment]
Hello @kriskbx 
Here is code

![php_code](https://cloud.githubusercontent.com/assets/12135394/7346998/8ab27b36-ed01-11e4-8e0b-8d301a46832d.png)

**Comment by kriskbx** [comment]
Are you actually using the library? It seems like you don't, coz there are no data attributes and no classes on the a tag as it should be. If you want to use **this** particular library, then repeat all the installation steps [here](https://github.com/kriskbx/whatsapp-sharing). If you dont't want to use the library and just want the url-scheme without any javascript overhead: make sure to encode your text and url with `urlencode( $str );`. One thing, though: your button will be displayed everywhere, even if the device doesn't support url-schemes or WhatsApp itself. So, in my opinion you should probably install this library.
