### ISSUE TITLE
Button not working upon clicking

### ISSUE THREAD

**Issue by juliousglori** [kriskbx/whatsapp-sharing#44]
Have implemented all says here http://whatsapp-sharing.com/ but when I run it and click the button, nothing works. anyone can help me solve this problem.
Thanks in advance

**Comment by kriskbx** [comment]
Noone can help you without code to look at.
Read this first: https://github.com/kriskbx/whatsapp-sharing/blob/master/ISSUES.md

**Comment by juliousglori** [comment]
see this page: http://stories.cromly.com/stories/article/dos-and-donts-of-hdb-renovations

**Comment by kriskbx** [comment]
Well, you used the uncompiled css, js and svg from the src directory... Of course this won't work.
Repeat **and follow** the installation steps. The compiled and production ready version is inside the `dist/` directory. You can also use the jsdelivr CDN: `//cdn.jsdelivr.net/whatsapp-sharing/1.3.2/whatsapp-button.js`

**Comment by juliousglori** [comment]
ok i have now updated the script src to use the jsdelivr cdn url. still nothing works :(
please see again this url: http://stories.cromly.com/stories/article/dos-and-donts-of-hdb-renovations

also when i browse it in iphone. a popup says 'cannot open the page because the address is invalid'
can u help me with this issues?
