### ISSUE TITLE
Button not working upon clicking

### ISSUE THREAD

**Issue by juliousglori** [kriskbx/whatsapp-sharing#45]
ref #44

**Comment by kriskbx** [comment]
You're still including the css from the `src/`directory...

**Comment by juliousglori** [comment]
but if i will not use the css and svg in the src, there is no design for the button, its just a plain link "Share"

**Comment by kriskbx** [comment]
The CSS as well as the SVG are compiled into the JavaScript file. The CSS will be applied to the button elements if the device supports WhatsApp - like an iPhone or Android smartphone. On your computer the button should **not** be visible at all. If you want to test if the button is displayed correctly on a computer, you could use the iOS or Android emulator as well as an useragent-switcher for your Browser. (Safari has this functionality by default by the way)

Take a look here: http://whatsapp-sharing.com
This site provides a step by step guide how to integrate the button in your page. You've done several things wrong at first. So, please do me a favor and read the guid again following each step accordingly without modifications on your own. There will be no problem afterwards.
