### ISSUE TITLE
How to share images on whatsapp with text / caption from my mobile site?

### ISSUE THREAD

**Issue by niravpatel1717** [kriskbx/whatsapp-sharing#50]
Hi,

I want to share images on whatsapp with text / caption from my mobile site.

Please help me.

Thanks in advance,
Nirav

**Comment by kriskbx** [comment]
https://github.com/kriskbx/whatsapp-sharing/issues/18

**Comment by niravpatel1717** [comment]
Thanks for your quick reply kriskbx.

Is there any other way for the same?

**Comment by kriskbx** [comment]
Nope this is not possible from the Browser.

**Comment by niravpatel1717** [comment]
Ok.

Thank you mate..

**Comment by Damian-Pumar** [comment]
Hello, you can use a plugin that I've created.

https://github.com/Damian-Pumar/Xamarin-Plugins

**Comment by kriskbx** [comment]
This is about frontend webdev not about any Android crap.
