### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by virtualgina** [kriskbx/whatsapp-sharing#51]
I have followed the instructions but am not seeing the button on the site. I am not sure I missed something since I only uploaded the one file whatsapp-button.js . I also installed the script before the /body hook on my website.  What am I missing? The url in question is http://daniesgranny.com and I have added the button code to the right sidebar above the sign-up form using a widget area.

**Comment by cn-tools** [comment]
hi! i have tested it on my android phone. there i can see the button and it works fine. maybe you test it on a 'normal' pc? the button is shown on specific 'navigator.userAgent' only.

**Comment by virtualgina** [comment]
Duh!!! I see it on my Android.   Thanks much. 


Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone if on my 

<div>-------- Original message --------</div><div>From: Clemens Neubauer <notifications@github.com> </div><div>Date:06/10/2015  1:32 AM  (GMT-05:00) </div><div>To: kriskbx/whatsapp-sharing <whatsapp-sharing@noreply.github.com> </div><div>Cc: Gina Storr <tropicalms@gmail.com> </div><div>Subject: Re: [whatsapp-sharing] Installation (#51) </div><div>
</div>hi! i have tested it on my android phone. there i can see the button and it works fine. maybe you test it on a 'normal' pc? the button is shown on specific 'navigator.userAgent' only.
