### ISSUE TITLE
whatsapp sharing working on android mobile browser but not working on android webview 

### ISSUE THREAD

**Issue by chaitu4027** [kriskbx/whatsapp-sharing#52]
![screenshot_2015-06-24-11-30-40](https://cloud.githubusercontent.com/assets/13028503/8323627/a911ae0e-1a64-11e5-93d7-d04ad014182d.png)

**Comment by kriskbx** [comment]
https://github.com/kriskbx/whatsapp-sharing/issues/39 duplicate
