### ISSUE TITLE
Problem when whatsapp not available

### ISSUE THREAD

**Issue by chaitu4027** [kriskbx/whatsapp-sharing#53]
We have implemented whatsapp sharing button to your website for the mobile compliance site. If whatsapp is installed the link is working fine and for the mobile devices without whatsapp showing "Web page not available." How to solve this issue.

**Comment by kriskbx** [comment]
Take a look at the FAQs.

https://github.com/kriskbx/whatsapp-sharing#4-if-whatsapp-is-not-installed-on-the-device-theres-an-error-message
