### ISSUE TITLE
Can't get it to work when loading content with ajax

### ISSUE THREAD

**Issue by tzfrs** [kriskbx/whatsapp-sharing#54]
Hello,

I'm using your WhatsApp-Sharing-Button! Awesome project, pretty easy and nice to implement. However, I'm having a problem with ajax requests.

I'm doing it like this:

    $.ajax({
        url: url
    }).done(function (data) {
        $('body').find('main:eq(1)').html(data);
        WASHAREBTN.crBtn();
    });

However, the URL is still the old one. When switching sites normally, the URL is the correct one, but with AJAX content loading I'm having this problem. How exactly would I solve this? What can I do to give you more information on this?

**Comment by kriskbx** [comment]
You could pass the right url via data-attribute to the button-elements before running the `crBtn()` method:

```
var content_container = $('body').find('main:eq(1)');
content_container.html($data);
content_container.find('a.wa_btn').data('href', 'http://insert-real-url-here');
WASHAREBTN.crBtn();
```

**Comment by kriskbx** [comment]
A better way is to set the data attribute serversided via php/ruby/... : `<a ... data-href="<?= get_real_url() ?>" ... >`

**Comment by tzfrs** [comment]
Okay, so if I understood that correctly.

Always fill out the data-href attribute (server side) and then, after loading the content, fill it automatically, with the current url, correct?

**Comment by kriskbx** [comment]
The library selects the current page url via `window.location.href` if the data-href attribute on a button element isn't set. In your situation, where the url doesn't match because of history.pushState or something else you should fill the attribute by yourself. The best way to do this, is by simply echoing out the correct url on the serverside.

**Comment by tzfrs** [comment]
All right, thanks!

2015-07-14 17:22 GMT+02:00 kris dot cool <notifications@github.com>:

**Comment by kriskbx** [comment]
You're welcome. :)

**Comment by canvasmanager** [comment]
I am using it in a directive in my angular app. I am able to make a call to WASHAREBTN.crBtn(scope); and get the button. The issue that I am facing is to set the url. I set the url by using this code:
element.find('a.wa_btn').data('href', scope.url); but is not getting set. I am still getting the window.url only. any ideas where I am making mistakes.

**Comment by manikmi** [comment]
I am using it in a directive in my angular app. I am able to make a call to WASHAREBTN.crBtn(scope); and get the button. The issue that I am facing is to set the url. I set the url by using this code:
element.find('a.wa_btn').data('href', scope.url); but is not getting set. I am still getting the window.url only. Any ideas, where I am making mistakes.
