### ISSUE TITLE
Magento and Whatsapp Button

### ISSUE THREAD

**Issue by domfitty** [kriskbx/whatsapp-sharing#56]
I'm trying to embed this button on a Magento installation
Here --> http://www.paolinestore.it/shop/inventami-una-storia-racconti-per-crescere.html the sample.

I added the code in a red box with the following text "Testing whatsapp", but the button is not showing and there are no errors on js console and WASHAREBTN returns 
Object { buttons: Array[0] }
Any ideas?

**Comment by kriskbx** [comment]
You used the JavaScript from the `src` folder. This file is not compiled and doesn't contain the required CSS. You've got to use this file: https://github.com/kriskbx/whatsapp-sharing/blob/master/dist/whatsapp-button.js

**Comment by domfitty** [comment]
It's true.... sorry for the inconvenience, I was wrong :-(

**Comment by kriskbx** [comment]
no prob. ;)
