### ISSUE TITLE
Ends up with "The address wasn't understood"

### ISSUE THREAD

**Issue by emfluenceindia** [kriskbx/whatsapp-sharing#61]
I am trying to integrate this in one of my websites by doing this:

**Step 1:** Downloaded the zip and put `whatsapp-button.js` in my application's content/wapp folder

**Step 2:** Put the following code just before `</body>`
`<script type="text/javascript"> if (typeof wabtn4fg === "undefined") { wabtn4fg = 1; h = document.head || document.getElementsByTagName("head")[0], s = document.createElement("script"); s.type = "text/javascript"; s.src = "http://localhost:61718/content/wapp/whatsapp-button.js"; h.appendChild(s) }</script>`

**Step 3:** Finally added the `anchor tag` in my page like this:
`<a href="whatsapp://send" data-text="Take a look at this awesome website:" data-href="http://localhost:61718/790220/2012-used-ferrari-458-spider-convertible-150000000" class="wa_btn wa_btn_s">Share</a>`

**Following two additional things I did with the anchor tag:**
a) Removed `style="display:none"`. Otherwise the button (text link) was not showing up
b) Added a URL to `data-href` property. I am not sure if I did right with these two

**Notes:**
- Developing the site with ASP.NET MVC 4 technology
- Currently I am viewing the site in desktop (tried by resizing to tablet/mobile views)

When I click the button I am landing on a page saying "The address wasn't understood". Please see screenshot.

Any help would be greatly appreciated.

![untitled](https://cloud.githubusercontent.com/assets/11072678/16331687/897681c0-3a0f-11e6-805f-107b830bd1b8.png)

**Comment by kriskbx** [comment]
The button won't show up on desktop browsers because there is no WhatsApp on desktop computers, that's intended behaviour. The URL scheme won't work on your desktop as well. Test it with your phone and it will work.
